# path to aap-juce directory.
AAP_JUCE_DIR=aap-juce

# path to application repo. The default is the submodule path.
APP_SRC_DIR=$(shell pwd)/external/Frequalizer

# base app name
APP_NAME=Frequalizer

# app build directory name. Usually repo name is good.
APP_BUILD_DIR=apps/Frequalizer

# diff file to app, generated by git diff. "-" if there is no patch.
PATCH_FILE=$(shell pwd)/apps/frequalizer-aap.patch

# diff depth, depending on the nested directory in the source tree, if patch exists.
PATCH_DEPTH=1

# Enable if it should skip metadata generator. Plugins need it, hosts don't.
# SKIP_METADATA_GENERATOR=1


include $(AAP_JUCE_DIR)/Makefile.common
